import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "How to Fill Out Form 8949 for Crypto: A Step-by-Step Guide (2025)",
  description:
    "Learn how to complete IRS Form 8949 for cryptocurrency transactions. Step-by-step instructions for reporting crypto sales, correcting cost basis, and using adjustment codes.",
  keywords: [
    "Form 8949 crypto",
    "Form 8949 guide",
    "how to fill out Form 8949",
    "crypto Form 8949",
    "IRS Form 8949 cryptocurrency",
    "Form 8949 adjustment code B",
  ],
  openGraph: {
    title: "How to Fill Out Form 8949 for Crypto (2025 Guide)",
    description: "Step-by-step guide to completing IRS Form 8949 for your crypto taxes.",
    type: "article",
    url: "https://basisguard.vercel.app/blog/form-8949-crypto-guide",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  headline: "How to Fill Out Form 8949 for Crypto: A Step-by-Step Guide",
  description: "Learn how to complete IRS Form 8949 for cryptocurrency transactions.",
  author: { "@type": "Organization", name: "BasisGuard", url: "https://basisguard.vercel.app" },
  publisher: { "@type": "Organization", name: "BasisGuard", url: "https://basisguard.vercel.app" },
  datePublished: "2026-03-02",
  dateModified: "2026-03-02",
  mainEntityOfPage: { "@type": "WebPage", "@id": "https://basisguard.vercel.app/blog/form-8949-crypto-guide" },
};

export default function Form8949CryptoGuidePage() {
  return (
    <div className="min-h-screen bg-offwhite">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <header className="bg-white border-b border-gray-100">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-semibold text-navy">
            Basis<span className="text-emerald">Guard</span>
          </Link>
          <Link href="/" className="text-sm text-slate hover:text-charcoal transition-colors">
            &larr; Back to Home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-card shadow-card p-8 sm:p-12">
          <div className="mb-3">
            <span className="inline-block bg-emerald/10 text-emerald-dark text-xs font-semibold px-3 py-1 rounded-full">
              Blog
            </span>
          </div>
          <h1 className="text-3xl font-bold text-navy mb-3">
            How to Fill Out Form 8949 for Crypto: A Step-by-Step Guide
          </h1>
          <p className="text-sm text-slate mb-8">Published March 2, 2026</p>

          <div className="prose prose-charcoal max-w-none space-y-6 text-charcoal leading-relaxed">
            <section>
              <p>
                If you sold, traded, or otherwise disposed of cryptocurrency in 2025, you need to report each
                transaction on IRS Form 8949. This guide walks you through exactly how to fill it out — especially
                when your 1099-DA is missing cost basis information.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Before You Start: What You Need</h2>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Your <strong>1099-DA</strong> from each crypto exchange</li>
                <li>Your <strong>transaction history</strong> (CSV download from each exchange)</li>
                <li>Your chosen <strong>accounting method</strong> (FIFO, LIFO, or HIFO)</li>
                <li>A <strong>blank Form 8949</strong> (IRS.gov or generated by tax software)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Step 1: Choose the Right Checkbox</h2>
              <p>
                At the top of Form 8949, you need to check one of three boxes. For most crypto traders in 2025:
              </p>
              <div className="bg-emerald/5 border border-emerald/20 rounded-card p-5 mt-4">
                <p className="font-semibold text-navy mb-2">Check Box B</p>
                <p className="text-sm">
                  &quot;Short-term transactions for which basis is <strong>not</strong> reported to the IRS.&quot;
                  Since the 1099-DA does not include cost basis for 2025, Box B is correct for most crypto sales.
                  Use a separate Form 8949 for Part II (long-term) transactions, also checking Box E (the long-term
                  equivalent of Box B).
                </p>
              </div>
              <p className="mt-3 text-sm text-slate">
                Box A is for transactions where basis <em>was</em> reported (stocks via 1099-B). Box C is for
                transactions with no 1099 at all (P2P sales, DEX trades).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Step 2: Fill Out Each Column</h2>
              <p>For each crypto sale, you need to complete one row with these columns:</p>
              <div className="space-y-3 mt-4">
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (a) — Description:</strong> The asset and quantity. Example: &quot;0.5 BTC&quot; or &quot;10 ETH&quot;</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (b) — Date acquired:</strong> When you originally bought or received the crypto. Use &quot;Various&quot; if you&apos;re selling from multiple purchase dates.</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (c) — Date sold:</strong> The date you sold, traded, or disposed of the crypto.</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (d) — Proceeds:</strong> The amount you received from the sale. This should match your 1099-DA.</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (e) — Cost basis:</strong> Your actual purchase price plus any fees. This is what the 1099-DA is missing.</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (f) — Adjustment code:</strong> Enter <strong>&quot;B&quot;</strong> to indicate you are correcting the basis reported on the 1099-DA.</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (g) — Adjustment amount:</strong> The difference between the 1099-DA basis ($0) and your actual basis. This will be a <em>negative</em> number (reduces your gain).</p>
                </div>
                <div className="bg-gray-50 rounded-btn p-4">
                  <p className="text-sm"><strong>Column (h) — Gain or loss:</strong> Column (d) minus column (e), adjusted by column (g). This is your actual taxable gain or loss.</p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Step 3: Example Entry</h2>
              <div className="overflow-x-auto mt-4">
                <table className="w-full text-sm border border-gray-200 rounded-btn overflow-hidden">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="text-left px-3 py-2 font-semibold border-b">(a)</th>
                      <th className="text-left px-3 py-2 font-semibold border-b">(b)</th>
                      <th className="text-left px-3 py-2 font-semibold border-b">(c)</th>
                      <th className="text-right px-3 py-2 font-semibold border-b">(d)</th>
                      <th className="text-right px-3 py-2 font-semibold border-b">(e)</th>
                      <th className="text-center px-3 py-2 font-semibold border-b">(f)</th>
                      <th className="text-right px-3 py-2 font-semibold border-b">(g)</th>
                      <th className="text-right px-3 py-2 font-semibold border-b">(h)</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="px-3 py-2 font-mono text-xs">0.5 BTC</td>
                      <td className="px-3 py-2 text-xs">03/15/2024</td>
                      <td className="px-3 py-2 text-xs">07/20/2025</td>
                      <td className="px-3 py-2 text-right font-mono text-xs">$47,000</td>
                      <td className="px-3 py-2 text-right font-mono text-xs">$40,000</td>
                      <td className="px-3 py-2 text-center font-mono text-xs">B</td>
                      <td className="px-3 py-2 text-right font-mono text-xs">-$40,000</td>
                      <td className="px-3 py-2 text-right font-mono text-xs font-semibold text-emerald-dark">$7,000</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <p className="mt-3 text-sm text-slate">
                Without the correction, the IRS would see a $47,000 gain. With it, they see the correct $7,000 gain.
                That&apos;s <strong>$9,600 saved</strong> at a 24% tax rate.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Step 4: Total and Transfer to Schedule D</h2>
              <p>
                After listing all your crypto sales, total each column at the bottom of Form 8949. Then transfer
                the totals to <strong>Schedule D</strong> of your Form 1040:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Short-term totals (Part I) go to Schedule D, Line 1b</li>
                <li>Long-term totals (Part II) go to Schedule D, Line 8b</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Common Mistakes to Avoid</h2>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li><strong>Wrong checkbox:</strong> Using Box A instead of Box B. Since basis isn&apos;t on the 1099-DA, you must use Box B.</li>
                <li><strong>Forgetting the adjustment code:</strong> Column (f) must have code &quot;B&quot; when correcting basis.</li>
                <li><strong>Mixing short-term and long-term:</strong> Use separate Form 8949 pages for each.</li>
                <li><strong>Rounding errors:</strong> Use exact figures from your transaction history, not rounded numbers.</li>
                <li><strong>Inconsistent accounting method:</strong> If you use FIFO for Bitcoin sales, you must use FIFO for all Bitcoin sales that year.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-navy mt-8 mb-3">Let BasisGuard Fill It Out for You</h2>
              <p>
                Manually filling out Form 8949 for dozens or hundreds of crypto transactions is tedious and
                error-prone. BasisGuard automates the entire process: upload your 1099-DA and exchange data,
                and we generate a completed Form 8949 PDF with all corrections applied, ready to file with
                your tax return.
              </p>
            </section>

            <div className="mt-10 bg-navy/5 rounded-card p-6 text-center">
              <h3 className="text-lg font-semibold text-navy mb-2">Generate Your Form 8949 Automatically</h3>
              <p className="text-sm text-slate mb-4">
                Upload your 1099-DA, connect your exchange, and get a corrected Form 8949 in 2 minutes.
              </p>
              <Link
                href="/upload"
                className="inline-block bg-emerald hover:bg-emerald-dark text-white font-semibold px-6 py-3 rounded-btn transition-colors"
              >
                Get Started Free &rarr;
              </Link>
            </div>

            <div className="mt-8 pt-6 border-t border-gray-100">
              <h3 className="text-sm font-semibold text-navy mb-3">Related Articles</h3>
              <div className="flex flex-wrap gap-3">
                <Link href="/guides/form-8949" className="text-sm text-emerald hover:text-emerald-dark transition-colors">
                  Form 8949 Reference Guide &rarr;
                </Link>
                <Link href="/blog/1099-da-wrong-cost-basis" className="text-sm text-emerald hover:text-emerald-dark transition-colors">
                  Why Your 1099-DA Is Wrong &rarr;
                </Link>
                <Link href="/blog/fix-missing-cost-basis" className="text-sm text-emerald hover:text-emerald-dark transition-colors">
                  How to Fix Missing Cost Basis &rarr;
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
        <p className="text-xs text-slate text-center leading-relaxed">
          <strong>Disclaimer:</strong> BasisGuard provides tax tools, not tax advice. Consult a qualified tax
          professional for guidance specific to your situation.
        </p>
      </footer>
    </div>
  );
}
